Fix CVProfile attribute access in process_last_month script
- Changed from cv_profile.profile['skills'] to cv_profile.skills
- Changed from cv_profile.profile['technologies'] to cv_profile.technologies
- Changed from cv_profile.profile['preferred_roles'] to cv_profile.preferred_roles
- Fixes AttributeError: 'CVProfile' object has no attribute 'profile'